# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "54323:5432"
